export const bookData = [
  {
    id: "1",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt & David Thomas",
    genre: "Programming",
    isbn: "978-0201616224",
    description: "A guide to becoming a better and more productive programmer.",
    copies: 5,
    available: true,
  },
  {
    id: "2",
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Programming",
    isbn: "978-0132350884",
    description: "Focuses on writing clean, maintainable code.",
    copies: 3,
    available: true,
  },
  {
    id: "3",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-help",
    isbn: "978-0735211292",
    description: "A proven framework for building good habits and breaking bad ones.",
    copies: 4,
    available: true,
  },
  {
    id: "4",
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    isbn: "978-0451524935",
    description: "A dystopian novel about totalitarianism and surveillance.",
    copies: 6,
    available: true,
  },
  {
    id: "5",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    isbn: "978-0061120084",
    description: "A story of racial injustice and childhood in the Deep South.",
    copies: 2,
    available: true,
  },
];
